baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emillynssuubo.github.io/" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: 'SsuuboE'
github_username: 'emillynssuubo'
linkedin_username: 'in//emillyn-ssuubo-baaa24148/'







